export const LOAD_REGIONS = 'LOAD_REGIONS';
export const SELECT_REGION = 'SELECT_REGION';
export const FILTER_REGIONS = 'FILTER_REGIONS';
export const TOGGLE_REGION = 'TOGGLE_REGION';

export const LOAD_PERMISSIONS = 'LOAD_PERMISSIONS';